name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # This will always pull the most recent stable version
          bun-version: latest

      - name: Install dependencies
        # --frozen-lockfile is the Bun equivalent of 'npm ci'
        run: bun install --frozen-lockfile

      - name: Test
        run: bun test
